#!/usr/bin/python
"""
Thanks to for the perl exemple
"""

import sys
import struct
import os
import subprocess
import shlex

pack_type = sys.argv[1]
recovery_folder = sys.argv[2]
temp_out_folder = sys.argv[3]
#skip 4 it's the -o
destination_file = sys.argv[5]
temp_recovery_cpio_gz = os.path.join(temp_out_folder, "temp-ramdisk.cpio.gz")


#This should be changed to some subprocess.PIPE 
command_line = "device/wiko/s9091/tools/ramdisk_cpio %s %s" % (recovery_folder, temp_recovery_cpio_gz)
args = shlex.split(command_line)

subprocess.call(args)

with open(temp_recovery_cpio_gz, "rb") as f:
    ramdisk = "".join(f.readlines())

string = struct.pack("4s I 32s 472s", "\x88\x16\x88\x58", len(ramdisk), "RECOVERY", "\xFF"*472)
string += ramdisk
with open(destination_file, "wb") as f:
    f.write(string)

