#!/usr/bin/python
"""
Thanks to https://github.com/bgcngm/mtk-tools for the perl exemple
We also need the mkbootimg provided by mediatek which adds a KERNEL 
flag in the generated .img file


Changelog:
    * Build ramdisk for recovery
    * Add ramdisk for rootfs
"""

import sys
import struct
import os
import subprocess
import shlex

pack_type = sys.argv[1]

if sys.argv[1] == "--recovery":
    tag = "RECOVERY"
elif sys.argv[1] == "--rootfs":
    tag = "ROOTFS"
else:
    print("Unknown option %s" % sys.argv[1])
    exit(1)

ramdisk_file = sys.argv[2]
#skip -o
destination_file = sys.argv[4]
with open(ramdisk_file) as f:
    ramdisk = "".join(f.readlines())

string = struct.pack("4s I 32s 472s", "\x88\x16\x88\x58", len(ramdisk), tag, "\xFF"*472)
string += ramdisk
with open(destination_file, "wb") as f:
    f.write(string)

